Add sprint 7 iteration 18
a-tho/monitor pull request #21
Opened 2024-01-25 09:18 UTC by a-tho

2024-03-03 09:05 UTC, maxlyaptsev commented
В профиле все ушло в создание структуры newDeflate и не видно реальной полезной нагрузки

<img width="525" alt="image" src="https://github.com/a-tho/monitor/assets/10906726/2433d7ba-d2c1-4301-95b9-f4c04d9ae96e">

2024-03-03 09:05 UTC, maxlyaptsev requested changes

2024-03-03 09:05 UTC, maxlyaptsev commented on internal/server/handlers_test.go
> +			resp, _ := testRequest(b, srv, http.MethodPost, "/"+UpdsPath, nil, &body)
в бенчмарках не должно ничего тестироваться,  тут только запуск кода. Лишний код в бенчмарках только смажет результат

2024-03-25 09:34 UTC, a-tho commented
- сделал документацию доступной
- исправил профили, теперь видна нагрузка и видна разница между суммарной аллокацией по памяти: убрал повторные аллокации буферов/компрессоров при каждой отправке метрик из agent в server, подробности на скрине (вкладка sample -> alloc_space)
- убрал тесты из бенчмарков
<img width="449" alt="Screenshot 2024-03-25 at 12 32 15" src="https://github.com/a-tho/monitor/assets/103521121/b9616089-9ed2-499a-95f3-ed3ee7d2d472">
<img width="200" alt="Screenshot 2024-03-25 at 12 32 29" src="https://github.com/a-tho/monitor/assets/103521121/10665d7f-fa9a-4ec0-8da3-0b6e45407e3f">

2024-03-25 16:09 UTC, maxlyaptsev commented
<img width="331" alt="image" src="https://github.com/a-tho/monitor/assets/10906726/1e12584a-e992-430c-a3dc-431f34fadec9">

Имеет смысл проверить этот код, почему столько памяти уходит на создание случайного числа. На каждом запросе не нужно создавать новую структуру. rand.Float64() будет эффективней

2024-03-25 16:19 UTC, merged